### ISSUE TITLE
Limiting auction to specific region

### ISSUE THREAD

**Issue by GrumpyCrouton** [virustotalop/ObsidianAuctions#24]
I found in the config where you can limit auction to a specific world, but I was wondering if you could limit it to a specific worldguard region? Using the 1.7.10 version.

I tried this way but it made it so no one could auction anywhere.

```
auction-scopes:
  default:
    name: Default Auction Scope
    type: regions
    regions:
    - mall
    config:
      disabled-commands-inscope: {}
```

I wish there was some documentation for this :(

**Comment by GrumpyCrouton** [comment]
By looking at the code I figured out you do it this way:

```
auction-scopes:
  servermall:
    name: Server Mall
    type: worldguardregion
    region-id: mall
    config:
      disabled-commands-inscope: {}
```

Luckily I know how to read code, I bet there are a lot of people that couldn't figure out how to do this.
