### ISSUE TITLE
Add translation override file for materials

### ISSUE THREAD

**Issue by virustotalop** [virustotalop/ObsidianAuctions#61]
Add language files instead of using minimessage translatable component. Support different item id formats depending on the version.
```yaml
'1:5': 'Andesite'
'ANDESITE': 'Andesite'
'MONSTER_EGG{EntityTag:{id:"creeper"}}': 'Creeper Spawn Egg'
CREEPER_SPAWN_EGG: 'Creeper Spawn Egg'
```
